# Generated by Django 2.1.2 on 2019-01-27 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('desciption', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('table', models.TextField(blank=True)),
                ('single_price', models.IntegerField()),
                ('multi_price', models.IntegerField()),
                ('corporate_price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('garaze', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
